package entities;
// Generated Feb 11, 2019 7:37:35 PM by Hibernate Tools 4.3.1



/**
 * Emisores generated by hbm2java
 */
public class Emisor  implements java.io.Serializable {


     private Integer idEmisor;
     private String nombre;
     private String direccion;
     private String rfc;

    public Emisor() {
    }

    public Emisor(String nombre, String direccion, String rfc) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.rfc = rfc;
    }
   
    public Integer getIdEmisor() {
        return this.idEmisor;
    }
    
    public void setIdEmisor(Integer idEmisor) {
        this.idEmisor = idEmisor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
}


